-- Create table
create table LOAD_STUDENAC_ENTRY_LEADGERS
(
  id                            NUMBER generated by default on null as identity,
  warehouse                     VARCHAR2(32767),
  store                         VARCHAR2(32767),
  item                          VARCHAR2(32767),
  item_type                     VARCHAR2(1),
  item_type_name                VARCHAR2(100),
  document_type                 VARCHAR2(50),
  document_type_name            VARCHAR2(100),
  document_id                   VARCHAR2(50),
  document_line                 NUMBER,
  document_date                 DATE,
  document_validation_date      DATE,
  document_validation_timestamp DATE,
  fifo_id                       NUMBER,
  quantity                      NUMBER,
  purchase_value                NUMBER,
  discount                      NUMBER,
  dependent_costs               NUMBER,
  wholesale_margin_value        NUMBER,
  wholesale_value               NUMBER,
  retail_margin_value           NUMBER,
  vat_value                     NUMBER,
  consumption_tax_value         NUMBER,
  return_fee_value              NUMBER,
  retail_value                  NUMBER,
  rounding_value                NUMBER,
  trosarina                     NUMBER,
  row_insert_timestamp          DATE,
  row_modified_timestamp        DATE
)
;
-- Create/Recreate primary, unique and foreign key constraints 
alter table LOAD_STUDENAC_ENTRY_LEADGERS
  add primary key (ID)
  using index
;
